Update configure-vwrs-edgeworker.md
Macrometacorp/docs pull request #1058
Opened 2023-12-05 18:43 UTC by diana-macrometa

This PR adds content from [DOC-975](https://macrometa.atlassian.net/browse/DOC-975) to the VWRs documentation.

2023-12-07 14:28 UTC, diana-macrometa commented
Reviewers, please review

2023-12-07 15:28 UTC, naimishvora-macrometa approved these changes
LGTM

2023-12-07 15:34 UTC, naimishvora-macrometa requested changes

2023-12-07 15:34 UTC, naimishvora-macrometa commented on docs/photoniq/vwrs/configure-vwrs-edgeworker.md
>  In the EdgeWorker, import the `VirtualWaitingRoom` class from the [vwroom-client](https://www.npmjs.com/package/vwroomclient) Node Package Manager (NPM). This integrates the VWRs with the EdgeWorker.
for this vwroom-client](https://www.npmjs.com/package/vwroomclient)

@diana-macrometa I think we should remove link from here as this is private repository so not accessible using link and instead of vwroom-client we changed name to photoniq-vwrs-client

2023-12-07 15:35 UTC, naimishvora-macrometa commented on docs/photoniq/vwrs/configure-vwrs-edgeworker.md
>  In the EdgeWorker, import the `VirtualWaitingRoom` class from the [vwroom-client](https://www.npmjs.com/package/vwroomclient) Node Package Manager (NPM). This integrates the VWRs with the EdgeWorker.
@rahul-naik1

2023-12-07 16:26 UTC, diana-macrometa commented on docs/photoniq/vwrs/configure-vwrs-edgeworker.md
>  In the EdgeWorker, import the `VirtualWaitingRoom` class from the [vwroom-client](https://www.npmjs.com/package/vwroomclient) Node Package Manager (NPM). This integrates the VWRs with the EdgeWorker.
Updated

2023-12-08 05:32 UTC, naimishvora-macrometa approved these changes
LGTM

2023-12-08 14:05 UTC, merged