Prerender synthetic interactions
Macrometacorp/docs pull request #1067
Opened 2024-01-03 22:07 UTC by diana-macrometa

Added documentation for viewing synthetic interactions.

@tushar-macrometa - Should I add info for the other tasks (create, update, delete)? A note in the intro said that right now only Macrometa people can perform those tasks, so I did not document them.

2024-01-05 13:15 UTC, sandro-macrometa requested changes

2024-01-05 13:15 UTC, sandro-macrometa commented on docs/photoniq/prerendering/synthetic-interactions/view-synthetic-interactions.md
> +- **Synthetic Interactions tab** - You can view synthetic interactions for all origins or for one origin on the Synthetic Interactions tab in the web console.
Here we only allow the user to view specific origin interactions. We don't have an "All origins" option.

2024-01-05 13:15 UTC, sandro-macrometa commented on docs/photoniq/prerendering/synthetic-interactions/view-synthetic-interactions.md
> +- **REST API** - Macrometa provides several API calls that allow you to view metrics for all origins or for one origin. You can also sort and set any time frame that you need.
For the REST API it is the same, you can only manage specific origin interactions.
Here there is no sort or time frame.

2024-01-05 13:15 UTC, sandro-macrometa commented on docs/photoniq/prerendering/synthetic-interactions/view-synthetic-interactions.md
> +- **Status** - Success status.
```suggestion
- **Status** - Whether the interaction is active.
```

2024-01-05 13:15 UTC, sandro-macrometa commented on docs/photoniq/prerendering/synthetic-interactions/view-synthetic-interactions.md
> +- **Status** - Success status.
```suggestion
- **Status** - Whether the interaction is active.
```

2024-01-05 13:15 UTC, sandro-macrometa commented on docs/photoniq/prerendering/synthetic-interactions/view-synthetic-interactions.md
> +- **Status** - Success status.
```suggestion
- **Status** - Whether the interaction is active.
```

2024-01-05 13:15 UTC, sandro-macrometa commented on docs/photoniq/prerendering/synthetic-interactions/view-synthetic-interactions.md
> +- **Status** - Success status.
```suggestion
- **Status** - Whether the interaction is active.
```

2024-01-05 13:15 UTC, sandro-macrometa commented on docs/photoniq/prerendering/synthetic-interactions/view-synthetic-interactions.md
> +- **Status** - Success status.
```suggestion
- **Status** - Whether the interaction is active.
```

2024-01-05 13:15 UTC, sandro-macrometa commented on docs/photoniq/prerendering/synthetic-interactions/view-synthetic-interactions.md
> +- **Status** - Success status.
```suggestion
- **Status** - Whether the interaction is active.
```

2024-01-05 13:19 UTC, sandro-macrometa commented
@diana-macrometa, this is what we have in the API reference. Maybe you can use the same texts:

```
Status - Whether the interaction is active.
Steps - Number of scrolls down to be performed.
Delay - Waiting time (in milliseconds) between scrolls.
URL Paths - Origin paths where the specific interaction is evaluated to be executed based on the operation attribute.
HTML Selector - HTML selector where the interaction is executed.
Wait After - Waiting time (in seconds) after the interaction is executed.
Sequence - Interaction execution order.
```

2024-01-08 15:24 UTC, diana-macrometa commented
@sandro-macrometa, applied your suggestions. 

Reviewers, please review.

2024-01-08 15:25 UTC, sandro-macrometa approved these changes

2024-01-08 15:36 UTC, merged