[DOC-447] Documentation for Anonymizer extension
Macrometacorp/docs pull request #258
Opened 2022-09-19 16:07 UTC by chandrashekhar-macrometa

Added documentation for anonymizer extension

2022-09-19 16:14 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +EXAMPLE 1:
If there is an EXAMPLE 1, that suggests that there will be more examples. We should either add EXAMPLE 2 or rename this just Example.

2022-09-19 17:29 UTC, diana-macrometa requested changes
This is a great start! I learned a lot. 

Consider adding a little more in the intro about why the user might want to use the anonymizer. Scrubbing medical data to prepare it for machine learning is one that springs to mind, but are there others?

If you add a second collection, then perhaps have the SINK be a stream? It would be great if your examples were useful code blocks that users can copy and repurpose for their own use.

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +# Anonymizer
```suggestion
---
sidebar_position: XX
title: Anonymizer
---
```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +The anonymizer extension provides a function for anonymizing various data types. This function returns a fake value for anonymizing
```suggestion
The anonymizer extension provides a function for anonymizing various data types. This function returns a fake value for anonymizing which matches the original data. For example, an email would be replaced with a fake email.
```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +Following data types are supported:
```suggestion
Macrometa supports the following data types:
```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    // Address
```suggestion
### Address

```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    // Name
```suggestion
### Name

```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    //Id
```suggestion
### ID

```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    // CreditCard
```suggestion
### Credit Card

```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    // Company
```suggestion
### Company

```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    // Name
Please make sure all commands are in alphabetical order.

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    // Address
Please put these lists in unordered format using hyphens as bullets.

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    // Education
```suggestion
### Education

```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    // Demographic
```suggestion
### Demographic

```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    // Internet
```suggestion
### Internet

```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    // Job
```suggestion
### Job

```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    // Medical
```suggestion
### Medical

```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    // PhoneNumber
```suggestion
### Phone Number

```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    // Name
Also make sure that the sections are listed in some sort of logical order. Alphabetical or by grouping subject matter, for example.

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    // Text
```suggestion
### Text
```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +
Only one line between paragraphs.

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +Syntax:
```suggestion
## Syntax

Anonymizer uses the following syntax:
```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +	pii:fake(STRING input.string, String fake.function, BOOL invalidate.cache)
The code should be in a code block, with the type defined.

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +QUERY PARAMETERS
```suggestion
## Query Parameters
```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    1. Insert following data into `patient_local` C8DB Collection
```suggestion
1. Insert following data into `patient_local` collection:
```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +        {"full_name": "John Doe", "ssn": "123-123-123", "email": "John.Doe@macrometa.com", "phone": "123-123-12345"}
```suggestion
{"full_name": "John Doe", "ssn": "123-123-123", "email": "John.Doe@macrometa.com", "phone": "123-123-12345"}
```

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +        {"full_name": "John Doe", "ssn": "123-123-123", "email": "John.Doe@macrometa.com", "phone": "123-123-12345"}
Put the code in code blocks for easy copy/paste.

2022-09-19 17:29 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    2. Following document would be shown on the `patient_public` collection
```suggestion
1. Following document would be shown on the `patient_public` collection:
```

2022-09-19 17:30 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +EXAMPLE 1:
```suggestion
## Example 1
```

2022-09-19 20:05 UTC, StoyanTc approved these changes

2022-09-21 17:46 UTC, diana-macrometa requested changes
Much better. A few more items to address.

Honestly, the example intrigues me. I look forward to understanding more about the use case!

2022-09-21 17:46 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +### Text
```suggestion
### Text

```

2022-09-21 17:46 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    ADDRESS_BUILDINGNUMBER
```suggestion
- ADDRESS_BUILDINGNUMBER
```

2022-09-21 17:46 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +    ADDRESS_BUILDINGNUMBER
This is the format for unordered lists in markdown. Please apply this to the rest of the lists.

2022-09-21 17:46 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +
Please delete the extra lines.

2022-09-21 17:46 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +		<invalidate.cache> - true, a different fake data will be generated at each call
What is this? Is it a parameter? I do not understand why it is not with the code block above or how to use it.

2022-09-21 17:46 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +		<invalidate.cache> - true, a different fake data will be generated at each call
Is this supposed to be part of the query parameters below?

2022-09-21 17:46 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +| invalidate.cache | An optional clean up cache   flag           | false         | BOOL                | Yes      | Yes     |
```suggestion
| invalidate.cache | An optional clean-up cache flag           | false         | BOOL                | Yes      | Yes     |
```

2022-09-21 17:46 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +
```suggestion
```

2022-09-21 17:46 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +
Add a sentence or two describing what the example is of. Something like, "This example shows how you might anonymize protected patient data for...<use case"

2022-09-22 18:09 UTC, diana-macrometa approved these changes
A few more minor suggestions, then good to go!

2022-09-22 18:09 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +sidebar_position: XX
```suggestion
```

2022-09-22 18:09 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +The anonymizer extension provides a function for anonymizing various data types. This function returns a fake value for anonymizing which matches the original data. For example, an email would be rep
```suggestion
The Anonymizer extension provides a function for anonymizing various data types. This function returns a fake value for anonymizing which matches the original data. For example, an email would be replaced with a fake email.
```

2022-09-22 18:09 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +This example shows how you might anonymize protected patient data. The patient needs to be hidden in the system so that he/she cannot be personally identified with it. Therefore, you need to obfuscat
Great paragraph! Please move this up under the Example heading, before the code block.

2022-09-22 18:09 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/anonymizer.md
> +
```suggestion

The code block does the following:

```

2022-09-29 06:04 UTC, merged