Migrate API permissions - redo
Macrometacorp/docs pull request #282
Opened 2022-09-27 21:42 UTC by jamesm-macrometa

2022-09-27 21:46 UTC, jamesm-macrometa commented
I think this section could still use more detail about different access levels and how they interact with each other, but this is a good start.

2022-09-27 22:01 UTC, diana-macrometa requested changes
This will be a great addition to the docs and really help our users! I have a few suggestions.

2022-09-27 22:01 UTC, diana-macrometa commented on docs/account-management/permissions/edit-permissions.md
> +1. Log in to Macrometa.
Add a link to the Macrometa login screen. You can grab that from another topic, lots in Collections and Query Workers.

2022-09-27 22:01 UTC, diana-macrometa commented on docs/account-management/permissions/edit-permissions.md
> +1. If you want to edit permissions for a user, click the **Users** tab and click the user in the list. Alternatively, click the **API Keys** tab and click the API key in the list.
```suggestion
1. If you want to edit permissions for a user, then click the **Users** tab and click the user in the list. Alternatively, click the **API Keys** tab and click the API key in the list.
```

2022-09-27 22:01 UTC, diana-macrometa commented on docs/account-management/permissions/edit-permissions.md
> +## Change Permissions for Users or API Keys
Please rewrite this as two separate tasks.

Change User Permissions

Change API Key Permissions

2022-09-27 22:01 UTC, diana-macrometa commented on docs/account-management/permissions/edit-permissions.md
> +1. On the Permissions tab, select the radio button for the permissions you want to assign.
Link to the topic where permissions are defined.

2022-09-27 22:01 UTC, diana-macrometa commented on docs/account-management/permissions/edit-permissions.md
> +1. Save the details for the user.
What do I click?

2022-09-27 22:01 UTC, diana-macrometa commented on docs/account-management/permissions/edit-permissions.md
> +1. Save the details for the user.
Also, this only applies to users.

2022-09-29 21:02 UTC, jamesm-macrometa commented
Thanks @diana-macrometa !  Incorporated your feedback.  Let me know if you spot anything else!

2022-09-29 21:05 UTC, diana-macrometa approved these changes
Looks good. One super minor edit.

Please create JIRA tickets to add SDK, CLI, and API tabs to these tasks. 

A lot of the SDK content already exists, like [Set Permissions](https://macrometa.com/docs/sdks/set-permissions) and [Create API Key}(https://macrometa.com/docs/sdks/create-api-key), we just need to organize it.

2022-09-29 21:05 UTC, diana-macrometa commented on docs/account-management/permissions/change-user-permissions.md
> +1. On the Permissions tab, select the radio button for the permissions you want to assign.  Refer to [Permissions](index.md) for information about each permission level.
```suggestion
1. On the Permissions tab, select the radio button for the permissions you want to assign. Refer to [Permissions](index.md) for information about each permission level.
```

2022-09-29 21:48 UTC, merged

2022-10-12 00:14 UTC, jamesm-macrometa commented
Hey @diana-macrometa - for some reason the changes I made to this branch don't appear in the [release-17-11 PR](https://github.com/Macrometacorp/docs/pull/281) despite this branch having been merged into that one.  Any idea why this might be the case?

2022-10-12 13:57 UTC, diana-macrometa commented
I might have accidentally removed them in a merge conflict. Most of those topics do not exist anymore since I did my rework to combine the stuff that was in the SDKs. I tried to make sure I captured all content changes, it's possible I missed something. Sorry!