update the Crypto App Getting Started and code example
Macrometacorp/docs pull request #353
Opened 2022-10-26 23:23 UTC by elof

This updates the Stream Worker code and adds information for how to configure the app in the Macrometa console.

2022-10-27 14:00 UTC, diana-macrometa requested changes
Good start. I made some suggestions.

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +### Configuring the Crypto App
```suggestion
### Configure the Crypto App
```

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +### Crypto App details
Headings should start at h2, not h3. Change throughout.

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +1. If you haven't already, [signup](https://auth.paas.macrometa.io/signup) for a free Macrometa Playground account.
```suggestion
1. If you haven't already, [sign up for a free Macrometa Playground account](https://auth.paas.macrometa.io/signup). 
```

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +1. If you haven't already, [signup](https://auth.paas.macrometa.io/signup) for a free Macrometa Playground account.
"signup" is a noun
"sign up" is a verb

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +2. Login into the [Macrometa Console](https://auth.paas.macrometa.io/) Go to the `Collections` tab and create a new `Doc` collection named `trades` with `collection stream enabled` checked.
```suggestion
2. Log in to the [Macrometa Console](https://auth.paas.macrometa.io/) Go to the Collections tab and create a new `Doc` collection named `trades` with `collection stream enabled` checked.
```

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +2. Login into the [Macrometa Console](https://auth.paas.macrometa.io/) Go to the `Collections` tab and create a new `Doc` collection named `trades` with `collection stream enabled` checked.
This is actually three steps. Please break it up.

Also, "login" is a noun. "Log in" is a verb.

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +2. Login into the [Macrometa Console](https://auth.paas.macrometa.io/) Go to the `Collections` tab and create a new `Doc` collection named `trades` with `collection stream enabled` checked.
Per the [Google Developer Style Guide](https://developers.google.com/style/ui-elements), UI items that you click are bold, not code style.

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +@App:name("Crypto-Trading-App")
The name, description, and version appear automatically. They are not needed here.

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +3. Open the `Stream Workers` tab and create a new `Stream Worker` named `Crypto-Trading-App`.
```suggestion
3. Click **Stream Workers**.
4. Click **New Stream Worker** named `Crypto-Trading-App`.
```

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +4. Copy and past the code example into the editor.
Link to the code example. Also, you should not have empty lines between numbered steps.

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +5. Click save and enable on location that is closest to where you are located around the globe.
```suggestion
5. Click **Save** and enable on location that is closest to where you are located around the globe.
```

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +5. Click save and enable on location that is closest to where you are located around the globe.
We don't want to validate the code? Is that a best practice? Also, give more specific instructions for how to enable the location.

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +6. Click publish.
```suggestion
6. Click **Publish**.
```

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +Once you the publish the Stream Worker, go over to our [live frontend](https://macrometacorp.github.io/tutorial-cryptotrading/) and use your Macrometa account credentials to log into your account. Se
If the user is using their credentials, then why are the demo credentials at the top of this page?

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +### Stream Worker Code
```suggestion
### Crypto App Stream Worker Code
```

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +### Stream Worker Code
Try to use specific headings.

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
>  whereas the strategy is kept in trades collection.
```suggestion
The strategy is kept in trades collection.
```

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
>  The close and average prices are stored in CryptoTraderQuotesAvgXXX streams
```suggestion
The close and average prices are stored in CryptoTraderQuotesAvgXXX streams.
```

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
>  Testing the Stream Application:
```suggestion
Test the Stream Application:
```

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
>      2. Start the GUI against the same federation
Not sure what this procedure here is for, didn't you give steps for this already? Either way, rewrite to remove "federation."

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
>  -- Streams for the http call requests
```suggestion
-- Streams for the HTTP call requests
```

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
>  -- Streams for the http call responses
```suggestion
-- Streams for the HTTP call responses
```

2022-10-27 14:00 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
>  -- Streams for the http call responses
Capitalize acronyms. Hypertext transfer protocol.

2022-10-27 20:07 UTC, elof commented
@diana-macrometa great, I accepted them all!

2022-10-27 20:09 UTC, diana-macrometa commented
> @diana-macrometa great, I accepted them all!

Cool! Btw, if you click the circling arrows next to a reviewer's name, then GitHub notifies them that the PR is ready for review. In my case, I get a Slack.

2022-10-27 20:13 UTC, diana-macrometa requested changes
@elof, please reread my comments. Accepting them does not help when I asked a question or requested a more complex change.

2022-10-27 20:13 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +### Crypto App details
Please change all headings at this level to h2.

2022-10-27 20:13 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
>  :::note
Remove this note.

2022-10-27 20:13 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +1. If you haven't already, [sign up for a free Macrometa Playground account](https://auth.paas.macrometa.io/signup).
Remove this step. It's covered in the following step for logging in. You might take a look at the tasks in the Streams or Collections sections to see how we do this.

2022-10-27 20:13 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +2. Log in to the [Macrometa Console](https://auth.paas.macrometa.io/) Go to the Collections tab and create a new `Doc` collection named `trades` with `collection stream enabled` checked.
Rewrite this as multiple steps. You can link to instructions for tasks like Create a Document Collection.

2022-11-03 00:24 UTC, elof commented on docs/apps/crypto-trading.md
> +Once you the publish the Stream Worker, go over to our [live frontend](https://macrometacorp.github.io/tutorial-cryptotrading/) and use your Macrometa account credentials to log into your account. Se
They can use the demo creds to see one in action without needed to set up their account.

2022-11-03 00:30 UTC, elof commented
@diana-macrometa submitted my updates

2022-11-03 14:36 UTC, diana-macrometa requested changes
Almost there!

2022-11-03 14:36 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +Read our [Blog Post](https://www.macrometa.com/blog/cryptocurrency-trading-building-a-multi-exchange-global-trading-bot) about exchange arbitrage and how the app works.
```suggestion
Read our blog post [How To Build A Crypto Arbitrage Trading Bot](https://www.macrometa.com/blog/cryptocurrency-trading-building-a-multi-exchange-global-trading-bot) to learn more about exchange arbitrage and how the app works.
```

2022-11-03 14:36 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +Read our [Blog Post](https://www.macrometa.com/blog/cryptocurrency-trading-building-a-multi-exchange-global-trading-bot) about exchange arbitrage and how the app works.
"Blog post" is extremely vague link text. Try to be as specific as possible, preferably matching the title of whatever you are linking to.

2022-11-03 14:36 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +2. Go to the Collections tab and create a new `Doc` collection named `trades` with `collection stream enabled` checked.
```suggestion
2. Go to the Collections tab and create a new document collection named `trades` with `collection stream enabled` checked. For more information about creating document collections, refer to [Create a Document Collection](ADD LINK TEXT HERE).
```

2022-11-03 14:36 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +6. Click **Save**. When you do we validate your code.
```suggestion
6. Click **Save**. 

    Macrometa validates your code.
```

2022-11-03 14:36 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +7. After you click save you will be prompted to select one or more locations to deploy your Stream Worker. Choose the location that is closest to where you are located, and click **Save**.
```suggestion
7. Select one or more locations to deploy your stream worker. Choose the location that is closest to where you are located, and then click **Save**.
```

2022-11-03 14:36 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +Once you the publish the Stream Worker, go over to our [live frontend](https://macrometacorp.github.io/tutorial-cryptotrading/) and use your Macrometa account credentials to log into your account. Se
```suggestion
After you the publish the stream worker, navigate to the [live frontend](https://macrometacorp.github.io/tutorial-cryptotrading/) and use your Macrometa account credentials to log in to your account. Select the location you deployed the stream worker to, and you will see the app come to life!
```

2022-11-03 14:36 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
> +6. Click **Save**. When you do we validate your code.
Can you add a little more here about the validation? What if it says the code is invalid? Is the validate line even useful in this context, or should we take it out?

2022-11-03 19:20 UTC, diana-macrometa approved these changes
One minor suggestion, then good to go!

2022-11-03 19:20 UTC, diana-macrometa commented on docs/apps/crypto-trading.md
>  |  `demo@macrometa.io` | `_system` | `crypto-trading-app` | [**Crypto Trading GUI**](https://macrometacorp.github.io/tutorial-cryptotrading/) |[github](https://github.com/Macrometacorp/tutorial-crypt
```suggestion
|  `demo@macrometa.io` | `_system` | `Crypto-Trading-App` | [**Crypto Trading GUI**](https://macrometacorp.github.io/tutorial-cryptotrading/) |[github](https://github.com/Macrometacorp/tutorial-cryptotrading)|
```

2022-11-03 20:13 UTC, merged

2023-05-22 20:03 UTC, rashimak commented
I need a Crypto trading bot