Akamai Function Worker as a Service
Macrometacorp/docs pull request #354
Opened 2022-10-27 01:05 UTC by jamesm-macrometa

This PR adds docs for integration of Akamai with Macrometa GDN.

2022-10-27 01:17 UTC, jamesm-macrometa commented
@diana-macrometa I formatted this following the same pattern as Query Workers, but I can easily change it to follow our more conventional formatting if that's preferable (e.g. Create Streams)

2022-10-27 02:29 UTC, jamesm-macrometa commented
@diana-macrometa @dlozina-macrometa @dwivedianurag Our docs on Akamai integration via GUI are ready for review.  

Do we want to include any additional concept info on Akamai and its integration with Macrometa?  If so we change the current Index into a Task, and create a new Index that contains concept stuff.

2022-10-27 14:55 UTC, diana-macrometa requested changes
Great start. The tasks are very tight, great stuff.

2022-10-27 14:55 UTC, diana-macrometa commented on docs/queryworkers/akamai/index.md
> +## Prerequisite
Also need to have an account and sufficient permissions.

2022-10-27 14:55 UTC, diana-macrometa commented on docs/queryworkers/akamai/index.md
> +This page describes how to integrate Akamai's edge worker functionality as a Macrometa function.
Should "edge worker" be capitalized? Seems like we are using a proper name here.

2022-10-27 14:55 UTC, diana-macrometa commented on docs/queryworkers/akamai/index.md
> +## Prerequisite
Probably should mention what permissions are needed. Admin? Read/write? For fabric or collection or what?

2022-10-27 14:55 UTC, diana-macrometa commented on docs/queryworkers/akamai/view-edge-workers.md
> +Macrometa displays a list of custom functions. Edge workers can be sorted by the type `Akamai`.
Bold, not code, for most UI elements. Refer to [Google Developer Style Guide](https://developers.google.com/style/ui-elements) for specifics.

2022-10-27 14:55 UTC, diana-macrometa commented on docs/queryworkers/akamai/index.md
> +## Add Integration
Put the integration tasks in a Manage Integrations topic.

2022-10-27 14:55 UTC, diana-macrometa commented on docs/queryworkers/akamai/generate-edge-workers.md
> +1. Click **Query Workers**.
Need two tasks in this topic.

Generate Edge Worker from Query Worker
Generate Edge Worker from Stream Worker

2022-10-27 14:55 UTC, diana-macrometa commented on docs/queryworkers/akamai/index.md
> +
The index should have more concept info as well as the information about this being a preview only. A note to that effect should be at the top of each topic as well.

2022-10-27 14:55 UTC, diana-macrometa commented on docs/queryworkers/akamai/index.md
> +
@dallas-macrometa or @dlozina-macrometa  might be able to help you with the concept info. What in broad strokes an Akamai edge worker is, how it extends Macrometa capabilities (JavaScript mostly), and maybe a couple use cases.

2022-10-27 14:55 UTC, diana-macrometa commented on docs/queryworkers/akamai/index.md
> +In Akamai, create a Property for your Macrometa GDN integration.
Great if we could link to the Akamai instructions for that.

2022-10-27 14:55 UTC, diana-macrometa commented on docs/queryworkers/akamai/delete-edge-workers.md
> +    Macrometa permanently deletes the edge worker. You can re-create the edge worker, but you cannot undo the deletion.
Check your linter. Looks like there is one space too many in front of this paragraph.

2022-10-27 14:55 UTC, diana-macrometa commented on docs/queryworkers/akamai/view-edge-workers.md
> +Macrometa displays a list of custom functions. Edge workers can be sorted by the type `Akamai`.
Probably should mention here that you can also view your edge workers in the list on Akamai.

2022-10-27 15:01 UTC, dallas-macrometa commented on docs/queryworkers/akamai/index.md
> +
I'll defer to @dlozina-macrometa here as I'm still very fuzzy on these new capabilities 🙈

2022-10-28 02:00 UTC, jamesm-macrometa commented on docs/queryworkers/akamai/generate-edge-workers.md
> +1. Click **Query Workers**.
I added a Stream Worker version of the topic, but unfortunately my phone started getting the internal error for the smoke environment so I can't actually check ☹️

2022-10-28 14:11 UTC, diana-macrometa commented
> Do we want to include any additional concept info on Akamai and its integration with Macrometa? If so we change the current Index into a Task, and create a new Index that contains concept stuff.

Yes, at least a sentence or two. There's great content you can lift from the video. However, we MUST have this content merged today, so we can go back later and refine it.

> I'm still a bit unclear on the "edge worker" vs "edge function" terminology and which goes where.

Edge worker = Akamai's thing that we are integrating with as of 17.11
Edge function = Macrometa's thing, not yet implemented. Not sure what it looks like yet, used to be called "function worker."

2022-10-28 14:18 UTC, diana-macrometa approved these changes
Love it. A few minor things, plus we need a sentence or two about the feature. Ideas:

Akamai edge workers are a powerful compute engine for creating and deploying microservices at the edge. The combination of Akamai’s compute engine with the Macrometa GDN allows you to develop microservices with powerful data storage and streaming capabilities, all running milliseconds from your users.

Edge workers allow you to use JavaScript to preprocess data or perform other tasks related to Macrometa streams and stream workers.

----
I'll watch the video again, send you any other blurbs I can pick out.

2022-10-28 14:18 UTC, diana-macrometa commented on docs/queryworkers/akamai/generate-edge-worker-stream.md
> +Generate an edge worker from a Stream worker.
```suggestion
Generate an edge worker from a stream worker.
```

2022-10-28 14:18 UTC, diana-macrometa commented on docs/queryworkers/akamai/generate-edge-worker-stream.md
> +1. Select a stream worker or [create a new one](../../cep/index.md).
When we actually write a task for creating a stream worker, let's update this link.

2022-10-28 14:18 UTC, diana-macrometa commented on docs/queryworkers/akamai/generate-edge-worker-stream.md
> +    - **Stream Name -** Add a name for the stream that will be created based on the old stream's code.
The old stream? What?

2022-10-28 14:18 UTC, diana-macrometa commented on docs/queryworkers/akamai/manage-integrations.md
> +:::note
Please add this note after the intro of each topic in this folder.

2022-10-28 14:18 UTC, diana-macrometa commented on docs/queryworkers/akamai/manage-integrations.md
> +- In Akamai, a Property created with your Macrometa GDN integration. Refer to [Create and configure a property](https://techdocs.akamai.com/api-definitions/docs/create-config-prop).
```suggestion
- In Akamai, a Property created with your Macrometa GDN integration. For more information about Akamai Properties, refer to [Create and configure a property](https://techdocs.akamai.com/api-definitions/docs/create-config-prop).
```

2022-10-28 14:29 UTC, diana-macrometa commented
From the demo video: 

Edge workers allow you to publish data to pipelines. You can continuously send data to an edge worker, which then can publish the data to a pipeline, a Macrometa stream, or both. 

Edge workers allow you to use JavaScript to preprocess or post-process data published to pipelines.

Edge workers allow you to query data inside streams and stream workers in real time. 

Sounds like the big selling points are:
- stateful processing (pre- or post-process data) with JavaScript
- publish to pipelines
- query real-time data in the pipeline, including data in motion (streams and stream workers)

-----
Hope that helps? I'm acting as a high-functioning parrot here, giving you what Durga said.

2022-10-28 15:09 UTC, jamesm-macrometa commented
> From the demo video:
> 
> Edge workers allow you to publish data to pipelines. You can continuously send data to an edge worker, which then can publish the data to a pipeline, a Macrometa stream, or both.
> 
> Edge workers allow you to use JavaScript to preprocess or post-process data published to pipelines.
> 
> Edge workers allow you to query data inside streams and stream workers in real time.
> 
> Sounds like the big selling points are:
> 
>     * stateful processing (pre- or post-process data) with JavaScript
> 
>     * publish to pipelines
> 
>     * query real-time data in the pipeline, including data in motion (streams and stream workers)
> 
> 
> Hope that helps? I'm acting as a high-functioning parrot here, giving you what Durga said.

Thank you!  This is very helpful.  I'll incorporate this info into the concept topic.

2022-10-28 15:24 UTC, dlozina-macrometa commented on docs/queryworkers/akamai/index.md
> +
EdgeWorkers enables developers to create and deploy microservices across more than a quarter of a million edge servers deployed around the globe. ([Edge Workers](https://developer.akamai.com/akamai-edgeworkers-overview)) Akamai has a vast content delivery network that extends Macrometa's points of presence worldwide. We allow users to build stateful applications across Akamai's CDN. That is how I understood partnership, we extend Edge Workers in a way that they can now save the state. Does this make sense? @dallas-macrometa @diana-macrometa @jamesm-macrometa

2022-10-28 15:31 UTC, jamesm-macrometa commented on docs/queryworkers/akamai/index.md
> +This page describes how to integrate Akamai's edge worker functionality as a Macrometa function.
Confirmed with Dino that Edge Worker is capitalized in Akamai's GUI.

2022-10-28 15:52 UTC, diana-macrometa commented
@jamesm-macrometa, I just noticed that Akamai EdgeWorker doesn't have the space between the last two words in their docs. Please update as necessary.

2022-10-28 15:59 UTC, jamesm-macrometa commented on docs/queryworkers/akamai/index.md
> +
Great stuff @dlozina-macrometa !  Thanks very much.

2022-10-28 16:01 UTC, jamesm-macrometa commented
@diana-macrometa I updated the Index topic to include concept info, including the helpful tidbits Dino provided.  Can you take a look at your earliest convenience?  Thanks!

2022-10-28 16:01 UTC, jamesm-macrometa commented
> @jamesm-macrometa, I just noticed that Akamai EdgeWorker doesn't have the space between the last two words in their docs. Please update as necessary.

Whoops, will fix that now.

2022-10-28 16:06 UTC, diana-macrometa approved these changes
Looks good, just a few minor suggestions, plus the EdgeWorker bit that it looks like you might have finished as I was typing this.

Please make a Jira to track returning to this content to add API, SDK, and CLI tabs as they become available.

2022-10-28 16:06 UTC, diana-macrometa commented on docs/queryworkers/akamai/manage-integrations.md
> +This page describes how to integrate Akamai's Edge Worker functionality as a Macrometa functions.
```suggestion
This page describes how to integrate Akamai's Edge Worker functionality with the Macrometa platform.
```

2022-10-28 16:06 UTC, diana-macrometa commented on docs/queryworkers/akamai/manage-integrations.md
> +- A Macrometa account with sufficient permissions to view and edit query workers.
```suggestion
- A Macrometa account with sufficient permissions to view and edit query workers or stream workers.
```

2022-10-28 16:06 UTC, diana-macrometa commented on docs/queryworkers/akamai/index.md
> +For more information about Akamai Edge Workers, refer to the [Akamai Edge Workers overview](https://developer.akamai.com/akamai-edgeworkers-overview).
```suggestion
For more information about Akamai EdgeWorkers, refer to the [Akamai Edge Workers Overview](https://developer.akamai.com/akamai-edgeworkers-overview).
```

2022-10-28 16:06 UTC, diana-macrometa commented on docs/queryworkers/akamai/manage-integrations.md
> +Add Akamai metadata from your Macrometa GDN environment.
```suggestion
Add Akamai metadata to your Macrometa GDN environment.
```

2022-10-28 16:06 UTC, diana-macrometa commented on docs/queryworkers/akamai/manage-integrations.md
> +## Add Integration
After the new API is rolled out, let's see if there's an API way to do this and add a tab. Something for next week.

2022-10-28 17:26 UTC, merged