SUP-115-Create-Stream-Application-Audit
Macrometacorp/docs pull request #408
Opened 2022-11-25 02:57 UTC by edgargarciamacrometa

2022-11-25 03:00 UTC, edgargarciamacrometa commented
I added collection.type='DOC', replication.type='GLOBAL' in some parts of the code, we do not support local collections at the moment, but CEP is taking local replication type as default, so the parameter needs to be defined in order to work. Also fixed this error integer -> int, 
Added example with CREATE TABLE GLOBAL SweetTable(product_id string, quantity int);
I think we don't support the following syntax: @sink(type="c8streams", stream="<STRING>", replication.type="<STRING>", @map(...)))

2022-11-28 15:54 UTC, diana-macrometa requested changes

2022-11-28 15:54 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
>  ### C8Streams
```suggestion
### Create Streams
```

2022-11-28 15:54 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
>  ### C8DB
It seems like this is the wrong heading. Maybe something about stream workers?

2022-11-28 15:54 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
>  Query Parameters:
```suggestion
Query parameters:
```

2022-11-28 15:54 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
>  ### C8DB
Avoid stacked headings, need an intro paragraph after the Table heading above. Also, I don't think we're using C8DB anymore, so this seems like the wrong heading text for this section.

2022-11-28 15:54 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
>  Stream applications will use the c8db with the default query parameters explained in the chart below.
Two things:
1. In all cases, replace "stream applications" with "stream workers." They used to call them stream applications, they don't anymore.
2. "C8DB" is also outdated terminology. Replace with "Macrometa" or the exact name of what is being accessed, like a collection.

2022-11-28 15:54 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +<td>Specifies if the replication type of the c8db collection. At the moment local collections are not allowed, type must be `global`</td>
```suggestion
<td>Specifies if the replication type of the collection. <b>Note:</b> Type must be `global`. Local collections are not currently allowed.</td>
```

2022-12-05 15:31 UTC, diana-macrometa commented
When this is ready for re-review, request one by clicking the circling arrows next to my name.

2022-12-05 17:51 UTC, diana-macrometa requested changes
A few more minor things, mostly formatting. We're getting close!

2022-12-05 17:51 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +<li>Partitions: Collections of stream definitions and queries separated from each other within a Stream worker for the purpose of processing events in parallel and in isolation</li>
```suggestion
<li>Partitions: Collections of stream definitions and queries separated from each other within a stream worker for the purpose of processing events in parallel and in isolation</li>
```

2022-12-05 17:51 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +1. Add the following sample stream worker.
```suggestion
1. Add the following sample stream worker:
```

2022-12-05 17:51 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
>  1. Click on `Save`.
```suggestion
1. Click **Save**.
```

2022-12-05 17:51 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +1. Click `Save` to save the stream worker.
```suggestion
1. Click **Save** to save the stream worker.
```

2022-12-05 17:51 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
>  1. Select all the regions to deploy your application in.
Is there a minimum of two here? I know there is a minimum for fabrics.

2022-12-05 17:51 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +### Create Streams
```suggestion

### Create Streams
```

2022-12-05 17:51 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
>  Example:
```suggestion

Example:
```

2022-12-05 17:51 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +```sql
```suggestion

```sql
```

2022-12-05 17:51 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
>  Example:
```suggestion

Example:
```

2022-12-05 17:51 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +Syntax:
```suggestion
Syntax:

```

2022-12-05 17:51 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +Stream worker will use the macrometa collections with the default query parameters explained in the chart below.
```suggestion
The stream worker will use the Macrometa collections with the default query parameters explained in the chart below.
```

2022-12-05 19:14 UTC, edgargarciamacrometa commented on docs/cep/tutorials/create-stream-app.md
>  1. Select all the regions to deploy your application in.
A client can have just 2 in playground active, but many more stream workers not enabled

2022-12-05 19:53 UTC, diana-macrometa approved these changes
Looks good to me

2022-12-06 17:14 UTC, merged