Fixing some typos & asking questions
Macrometacorp/docs pull request #414
Opened 2022-12-01 00:42 UTC by jesusgonzalez12

Aside from fixing a few typos, I changed "StreamApp" reference to "Stream Worker". If you consider it should be "stream worker" is better, go ahead.

A few other questions I have is:
1) I did not understand the line "Here, the keys of payload mapping can be defined using the dot notation as a.b.c, or using any constant string value as '$abc'.", and I cannot see an example of that use case. If this goes here, an example would greatly help. 2) I think the line  "unavailable or coursing errors" should be "unavailable or causing errors".
3) We have this in one query: "CREATE SOURCE <source_name> WITH (type = 'source_type'". Shouldn't it be "... WITH (source.type = ..."?

2022-12-01 15:04 UTC, diana-macrometa commented
@StoyanTc, can you answer the questions in the description?

2022-12-01 15:16 UTC, diana-macrometa requested changes

2022-12-01 15:16 UTC, diana-macrometa commented on docs/cep/query-guide/stream.md
> +| `database` | Allow the Stream Worker to consume events from collections (doc, graphs) running in the same or different geo fabric. |
Do not capitalize stream worker unless you are referring to the UI, such as "click **Stream Worker**.

2022-12-01 15:16 UTC, diana-macrometa commented on docs/cep/query-guide/stream.md
>  **Syntax**
Change these bold lines pretending to be headings into actual headings.

2022-12-01 15:16 UTC, diana-macrometa commented on docs/cep/query-guide/stream.md
>  Note: Details on writing processing logics via [queries](#query) will be explained in later sections.
```suggestion
:::note
Details on writing processing logics via [queries](#query) will be explained in later sections.
:::
```

2022-12-01 15:16 UTC, diana-macrometa commented on docs/cep/query-guide/stream.md
> +The Stream Worker extends the above use-case by adding failure generation and error handling with the use of [queries](#query) is as follows.
```suggestion
The stream worker extends the above use case by adding failure generation and error handling with the use of [queries](#query) as follows.
```

2022-12-01 15:50 UTC, StoyanTc commented
> @diana-macrometa @jesusgonzalez12  - 
1. I cannot understand your question, please provide a link to which part of doc you're pointing to?
2. The original statement is correct, ref. https://docs.google.com/document/d/1Qbgkhl44AYOmkSp6JfT_iDL9IVYRxRFE/edit

2022-12-02 00:41 UTC, jesusgonzalez12 commented on docs/cep/query-guide/stream.md
> +| `database` | Allow the Stream Worker to consume events from collections (doc, graphs) running in the same or different geo fabric. |
ok, thanks.

2022-12-02 00:58 UTC, jesusgonzalez12 commented on docs/cep/query-guide/stream.md
>  **Syntax**
changing for "Syntax". Is that right?

2022-12-02 01:10 UTC, jesusgonzalez12 commented
Hi @StoyanTc 

1) Here https://macrometa.com/docs/cep/query-guide/stream#sink on "Map Payload" subsection, last paragraph.
2) OK, good to know, thanks.

2022-12-09 16:26 UTC, diana-macrometa commented
What is the status of this, @jesusgonzalez12 ?

2022-12-11 23:43 UTC, jesusgonzalez12 commented
Thanks for keeping an eye @diana-macrometa.

The only thing pending is my question about the added paragraph I've been talking about, my point number one question in a previous comment.

@StoyanTc, I have provided the location of the paragraph. Would be great to have more context or an example.

2022-12-12 09:55 UTC, StoyanTc commented
> Thanks for keeping an eye @diana-macrometa.
> 
> The only thing pending is my question about the added paragraph I've been talking about, my point number one question in a previous comment.
> 
> @StoyanTc, I have provided the location of the paragraph. Would be great to have more context or an example.

@jesusgonzalez12 - 

- If the key is `$abc='some value'` the output will be `{"$abc": "some value"}`. This is just a constant.
- If the key is `a.b.c="some value", the output will be nested json like `{"a" : {"b":{"c":"some value"}}}`

2022-12-13 01:06 UTC, jesusgonzalez12 commented
Thanks @StoyanTc.

@diana-macrometa, adding Stoyan's example can improve de doc. What do you think?

2022-12-13 15:28 UTC, diana-macrometa approved these changes
Looks good!

2022-12-13 15:28 UTC, merged