Adding useful info
Macrometacorp/docs pull request #415
Opened 2022-12-01 00:56 UTC by jesusgonzalez12

I've added a way in which users can check their local version of the SDK and a couple of useful links so they can view more docs.

Maybe it would be a good idea to change the title from "Install SDKs" to "Manage SDKs" or to "Getting started with SDKs". Another option is to divide the sections into different files/web pages.

2022-12-01 15:07 UTC, diana-macrometa requested changes
A couple suggestions, then it will be good to go. And you are right, we're getting to the point where we should probably break this topic up into separate ones.

2022-12-01 15:07 UTC, diana-macrometa commented on docs/sdks/install-sdks.md
> +jsC8: [https://www.npmjs.com/package/jsc8](https://www.npmjs.com/package/jsc8)
```suggestion
- jsC8: [https://www.npmjs.com/package/jsc8](https://www.npmjs.com/package/jsc8)
```

2022-12-01 15:07 UTC, diana-macrometa commented on docs/sdks/install-sdks.md
> +pyC8: [https://pyc8.readthedocs.io/en/latest](https://pyc8.readthedocs.io/en/latest)
```suggestion
- pyC8: [https://pyc8.readthedocs.io/en/latest](https://pyc8.readthedocs.io/en/latest)
```

2022-12-01 15:07 UTC, diana-macrometa commented on docs/sdks/install-sdks.md
> +jsC8: [https://www.npmjs.com/package/jsc8](https://www.npmjs.com/package/jsc8)
Please change the links for both of these to the GitHub repos.

2022-12-01 15:07 UTC, diana-macrometa commented on docs/sdks/install-sdks.md
> +## View currently installed version of the SDK
```suggestion
## Check Installed SDK Version
```

2022-12-01 15:07 UTC, diana-macrometa commented on docs/sdks/install-sdks.md
> +To know the currently installed version of the SDK, run the following command
```suggestion
To check which version of the SDK is currently installed, run the following command in your terminal:
```

2022-12-02 00:40 UTC, jesusgonzalez12 commented
Hi @diana-macrometa. Followed recommendations. PR updated. Thanks.

2022-12-02 15:01 UTC, diana-macrometa commented
@jesusgonzalez12, the best way to get another review is click the circling arrows next to a reviewer's name. GitHub then sends a notification.

2022-12-02 15:02 UTC, diana-macrometa approved these changes
Looks good!

2022-12-02 15:02 UTC, diana-macrometa commented on docs/sdks/install-sdks.md
> +jsC8: [https://github.com/macrometacorp/jsC8](https://github.com/macrometacorp/jsC8)
```suggestion
- jsC8: [https://github.com/macrometacorp/jsC8](https://github.com/macrometacorp/jsC8)
```

2022-12-02 15:02 UTC, diana-macrometa commented on docs/sdks/install-sdks.md
> +pyC8: [https://github.com/Macrometacorp/pyC8](https://github.com/Macrometacorp/pyC8)
```suggestion
- pyC8: [https://github.com/Macrometacorp/pyC8](https://github.com/Macrometacorp/pyC8)
```

2022-12-02 15:09 UTC, merged

2022-12-07 22:28 UTC, jesusgonzalez12 commented
Thanks for the tip @diana-macrometa, will take it into account next time