[DOC-448] Document Sentiment Analysis [master]
Macrometacorp/docs pull request #429
Opened 2022-12-05 14:47 UTC by ashish-macrometa

- Updated documentation for Sentiment analysis  
- Updated example for Sentiment analysis 
- Fixes [[DOC-448](https://macrometa.atlassian.net/browse/DOC-448)]

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

2022-12-05 15:15 UTC, StoyanTc approved these changes

2022-12-05 15:43 UTC, diana-macrometa requested changes
A few minor suggestions.

2022-12-05 15:43 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/sentiment.md
> +It contains 3300+ words with a polarity score associated with each word.
```suggestion
It contains more than 3,300 words with a polarity score associated with each word.
```

2022-12-05 15:43 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/sentiment.md
> +This provides the sentiment value for a given string as per the AFINN word list. The sentiment value ranges from -5 to +5.
Didn't we just say this on line 2? I suggest removing it in one place or the other.

2022-12-05 15:43 UTC, diana-macrometa commented on docs/cep/reference/extensions/execution/sentiment.md
>  Syntax
```suggestion
## Syntax
```

2022-12-06 15:09 UTC, diana-macrometa commented
@ashish-macrometa, when this is ready for re-review, click the circling arrows next to my name. GitHub will send me a notification.

2023-01-09 16:50 UTC, diana-macrometa commented
@ashish-macrometa, are you planning to finish this?

2023-01-17 17:01 UTC, diana-macrometa commented
@ashish-macrometa, are you planning to finish this, or should we close the PR?

2023-01-24 20:41 UTC, diana-macrometa commented
@ashish-macrometa or @StoyanTc, please finalize this topic. Respond to the suggestions and resolve conflicts.

2023-01-25 09:06 UTC, StoyanTc approved these changes

2023-01-25 15:45 UTC, diana-macrometa approved these changes

2023-01-25 15:49 UTC, closed without merging