SUP-120 StreamWorker Summarising Data Audit
Macrometacorp/docs pull request #491
Opened 2022-12-19 13:45 UTC by koshy-thomas

1. AGGREGATION are created as local collections by default so store.type='database' and store.replication.type='global' are needed to create an aggregation collection as global collection.
2. TradeRetrievalSummaryStream to retrieve aggregation events is not needed at all (removing it) and the output Stream TradeSummaryStream definition.
3. timestamp attribute in ProductionStream is not required. 
4. Log Stream needs SINK annotation and type='logger' instead of type='log'
5. #window.lengthBatch() and #window.time() don't work anymore simply "window lengthBatch()" and "window time()" works fine

2022-12-19 15:28 UTC, diana-macrometa requested changes

2022-12-19 15:28 UTC, diana-macrometa commented on docs/cep/tutorials/summarizing-data.md
> +2. To retrieve aggregations, you need to make retrieval requests. To process these requests let's define a stream as follows.
```suggestion
2. To retrieve aggregations, you need to make retrieval requests. To process these requests, let's define a stream as follows:
```

2022-12-19 15:28 UTC, diana-macrometa commented on docs/cep/tutorials/summarizing-data.md
>  1. Open the `TradeApp` stream application.
How do you open it? Also, it should be a stream worker.

2022-12-19 15:28 UTC, diana-macrometa commented on docs/cep/tutorials/summarizing-data.md
> +3. To retrieve and process the events, add a new query as follows.
```suggestion
3. To retrieve and process the events, add a new query as follows:
```

2022-12-19 15:28 UTC, diana-macrometa commented on docs/cep/tutorials/summarizing-data.md
>  2. To capture details about each production run, define an input stream as follows.
```suggestion
2. To capture details about each production run, define an input stream:
```

2022-12-19 15:28 UTC, diana-macrometa commented on docs/cep/tutorials/summarizing-data.md
>  3. To publish the production for the last hour, define the output stream as follows.
```suggestion
3. To publish the production for the last hour, define the output stream:
```

2022-12-19 15:28 UTC, diana-macrometa commented on docs/cep/tutorials/summarizing-data.md
> +        A sink annotation is connected to the output stream to log the output events. You can view the logged events by simply clicking on the `Log Viewer` button on the stream worker editor tab. For
```suggestion
        A sink annotation is connected to the output stream to log the output events. You can view the logged events by clicking on the **Log Viewer** on the stream worker editor tab. For more information about adding sinks to publish events, see the [Publishing Data](publishing-data.md).
```

2022-12-19 15:28 UTC, diana-macrometa commented on docs/cep/tutorials/summarizing-data.md
>  4. To define how the output is derived, add the `select` statement as follows:
```suggestion
4. To define how the output is derived, add the `select` statement:
```

2022-12-20 03:25 UTC, koshy-thomas commented on docs/cep/tutorials/summarizing-data.md
>  1. Open the `TradeApp` stream application.
Yup it should be worker. Changed it may you review again

2022-12-20 15:17 UTC, diana-macrometa approved these changes

2022-12-20 15:17 UTC, diana-macrometa commented on docs/cep/tutorials/summarizing-data.md
> +4. The completed stream worker is as follows.
```suggestion
4. The completed stream worker is as follows:
```

2022-12-20 16:21 UTC, merged