[DOC-460] Add SW example to understand usecase for sink, source, table and window [master]
Macrometacorp/docs pull request #535
Opened 2022-12-30 20:21 UTC by ashish-macrometa

- Add SW example to understand usecase for sink, source, table and window
- Fixes [[DOC-460](https://macrometa.atlassian.net/browse/DOC-460)]

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

2022-12-31 06:58 UTC, StoyanTc approved these changes

2023-01-03 18:34 UTC, diana-macrometa requested changes

2023-01-03 18:34 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +In the application below, a Macrometa document based collection plays role of `source` to our SW IntrusionDetectionSystem.
```suggestion
In the application below, a Macrometa document-based collection plays role of `source` to our SW IntrusionDetectionSystem.
```

2023-01-03 18:34 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +Now it is quite possible that your application, `IntrusionDetectionSystem` may get burst of events having the same IP, and you need to gauge  
```suggestion
It is quite possible that your application, `IntrusionDetectionSystem`, might get burst of events having the same IP, and you need to gauge  
```

2023-01-03 18:34 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +In our IntrusionDetectionSystem application, we have associated a `sliding window` of 2 seconds on incoming events. The window will hold all the events that appear
```suggestion
In our IntrusionDetectionSystem application, we have associated a `sliding window` of two seconds on incoming events. The window will hold all the events that appear
```

2023-01-03 18:34 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +within 2 seconds. Further Stream QL is grouping all the events by IP and if the count on any of these groups is more than 50, i.e., more than 50 events occurred
```suggestion
within two seconds. Further Stream QL is grouping all the events by IP and if the count on any of these groups is more than 50, i.e., more than 50 events occurred
```

2023-01-03 18:34 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +from the same IP within 2 seconds, we can assume this is suspicious traffic. 
```suggestion
from the same IP within two seconds, then we can assume this is suspicious traffic. 
```

2023-01-03 18:34 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +If they match, we raise an alarm by adding a event to a `sink`. Sink is an abstraction for an egress event, which serves as an output for the Stream Worker application,
```suggestion
If they match, then we raise an alarm by adding an event to a `sink`. Sink is an abstraction for an egress event, which serves as an output for the stream worker,
```

2023-01-03 18:34 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +convert them to various data formats, and publish them to a stream or external endpoints like HTTP/REST ,database, log, JMS, email or as in this case, a Macrometa stream.
```suggestion
convert them to various data formats, and publish them to a stream or external endpoints like HTTP/REST ,database, log, JMS, email, or as in this case, a Macrometa stream.
```

2023-01-03 18:34 UTC, diana-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +
Only one empty line between the example and the next heading.

2023-01-04 00:14 UTC, jamesm-macrometa requested changes, later dismissed
A few minor changes requested

2023-01-04 00:14 UTC, jamesm-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +In the application below, a Macrometa document based collection plays role of `source` to our SW IntrusionDetectionSystem.
```suggestion
In the following application, a Macrometa document-based collection plays role of `source` to our SW IntrusionDetectionSystem.
```

2023-01-04 00:14 UTC, jamesm-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +this traffic in some way. Maybe 50 requests in a couple of seconds from the same IP can be considered suspicious traffic.
```suggestion
```

Moved content to previous line

2023-01-04 00:14 UTC, jamesm-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +Now it is quite possible that your application, `IntrusionDetectionSystem` may get burst of events having the same IP, and you need to gauge  
```suggestion
Your application, `IntrusionDetectionSystem`, might get burst of events from IP, and you need to gauge this traffic. For example, 50 requests in a couple of seconds from the same IP can be considered suspicious traffic.
```

2023-01-04 00:14 UTC, jamesm-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +In addition to the window, we have reference data for our application, i.e., `Table`.  A table is a stored collection of events, and its schema is defined via the
```suggestion
In addition to the window, we have a `Table` which serves reference data for our application.  A table is a stored collection of events, and its schema is defined via the table definition. Unlike `stream`, `table` is stateful and supports interactive queries for the state of the stored events. In our case `SuspiciousIPTable` stores pre-defined suspicious IPs which we are using to verify if it matches IPs in suspicious traffic.
```

Is it correct to say that a table "serves" reference data?  Or should we rephrase this?

2023-01-04 00:14 UTC, jamesm-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +table definition. Unlike `stream`, `table` is stateful and supports interactive queries for the state of the stored events. In our case `SuspiciousIPTable` stores
```suggestion
```

Moved content to previous line

2023-01-04 00:14 UTC, jamesm-macrometa commented on docs/cep/tutorials/create-stream-app.md
> +pre-defined suspicious IPs which we are using to verify if it matches IPs in suspicious traffic. 
```suggestion
```

Moved content to previous line

2023-01-04 16:35 UTC, diana-macrometa approved these changes

2023-01-09 16:51 UTC, diana-macrometa commented
@ashish-macrometa, please review the remaining suggestions.

2023-01-24 20:40 UTC, diana-macrometa commented
@ashish-macrometa or @StoyanTc, please finalize this topic. Respond to the suggestions and resolve conflicts.

2023-01-25 15:58 UTC, merged