Updated syntax
Macrometacorp/docs pull request #537
Opened 2022-12-31 23:28 UTC by jesusgonzalez12

Updated the syntax of templates and queries to better reflect stream worker's capabilities.

2023-01-03 15:19 UTC, diana-macrometa requested changes

2023-01-03 15:19 UTC, diana-macrometa commented on docs/cep/store-rdbms-plugin.md
> +Note: Make sure the stream is previously defined with:
```suggestion
Make sure the stream is defined with:
```

2023-01-03 15:19 UTC, diana-macrometa commented on docs/cep/store-rdbms-plugin.md
> +Note: Make sure the stream is previously defined with:
```suggestion
Make sure the stream is defined with:
```

2023-01-03 15:19 UTC, diana-macrometa commented on docs/cep/store-rdbms-plugin.md
>  Use the following template to create a Procedure function:
```suggestion
Use the following template to create a procedure function:
```

2023-01-03 15:19 UTC, diana-macrometa commented on docs/cep/store-rdbms-plugin.md
> +Note: Make sure the stream is previously defined with:
```suggestion
Make sure the stream is defined with:
```

2023-01-03 15:19 UTC, diana-macrometa commented on docs/cep/store-rdbms-plugin.md
> +Note: Make sure the stream is previously defined with:
```suggestion
Make sure the stream is defined with:
```

2023-01-03 15:19 UTC, diana-macrometa commented on docs/cep/store-rdbms-plugin.md
> +Note: Make sure the stream is previously defined with:
```suggestion
Make sure the stream is defined with:
```

2023-01-03 15:19 UTC, diana-macrometa commented on docs/cep/store-rdbms-plugin.md
> +Note: Make sure the stream is previously defined with:
```suggestion
Make sure the stream is defined with:
```

2023-01-04 19:42 UTC, jesusgonzalez12 reviewed
Thanks for the recommendations @diana-macrometa

2023-01-09 20:51 UTC, diana-macrometa approved these changes

2023-01-09 20:56 UTC, merged