Essentials revision
Macrometacorp/docs pull request #73
Opened 2022-06-07 04:38 UTC by jamesm-macrometa

Revised Essentials overview page and renamed it "Introduction."  Moved redundant info into appropriate quickstart sections.

@astrotars I added a new "Quickstart" file under Collections, I'm going to need your help properly adding it to the Docusaurus structure.

cc @diana-macrometa

2022-06-07 16:29 UTC, astrotars commented
@jamesm-macrometa I pushed a couple of updates, including some tweaks to position Quickstart as the first item in the collections directory.

Some updates that were made:

1. Broken path names due to filename changes

<img width="857" alt="Screen Shot 2022-06-07 at 10 14 08 AM" src="https://user-images.githubusercontent.com/1328388/172433198-b31e596a-8db8-4174-842d-9ff93e8cb5d8.png">

2. Fixed broken path to image

<img width="774" alt="Screen Shot 2022-06-07 at 10 14 20 AM" src="https://user-images.githubusercontent.com/1328388/172433966-13a318fa-0af2-4e72-a58f-b762d98f5c12.png">

3. Updated `position` in `_category_.json` files in `collections`

<img width="269" alt="Screen Shot 2022-06-07 at 10 23 39 AM" src="https://user-images.githubusercontent.com/1328388/172434079-b95e83f6-91b7-4576-b59c-097c6bcb092a.png">

2022-06-07 16:30 UTC, astrotars approved these changes
👍 @jamesm-macrometa

2022-06-07 16:53 UTC, diana-macrometa requested changes
Looks good, needs a few changes.

2022-06-07 16:53 UTC, diana-macrometa commented on docs/cep/quickstart.md
> +# Example
Why is there an h1 this far down the page? There should only be one h1, and it should be at the top of the page.

2022-06-07 16:53 UTC, diana-macrometa commented on docs/collections/documents/quickstart.md
> +# Example
Why is there an h1 on line 88 here?

2022-06-07 16:53 UTC, diana-macrometa commented on docs/collections/graphs/quickstart.md
> +# Example
Another h1 in the wrong place. Needs to be h2 or above.

2022-06-07 16:53 UTC, diana-macrometa commented on docs/collections/keyvalue/quickstart.md
> +In GDN, each document stored in a collection contains a `_key`, and the rest of the document is its *value*. The only key-value operations available are key lookups (single & batch) and key-value pai
```suggestion
In GDN, each document stored in a collection contains a `_key`, and the rest of the document is its *value*. The only key-value operations available are key lookups (single and batch) and key-value pair insertions and updates. If no sharding attribute is specified, `_key` is used for sharding the data instead.
```

2022-06-07 16:53 UTC, diana-macrometa commented on docs/essentials/introduction.md
> +
```suggestion
```

2022-06-07 16:53 UTC, diana-macrometa commented on docs/essentials/introduction.md
> +## Sharding & Replication
```suggestion
## Sharding and Replication
```

2022-06-07 16:53 UTC, diana-macrometa commented on docs/essentials/introduction.md
> +## Sharding & Replication
Avoid stacked headings. Need a paragraph of plain text between these two.

2022-06-07 16:53 UTC, diana-macrometa commented on docs/essentials/introduction.md
> +> Subscriptions are local to a GDN datacenter.
What is this? Is it intended to be a note?

2022-06-07 16:53 UTC, diana-macrometa commented on docs/streams/quickstart.md
>  - Seamless geo-replication of messages across regions
James, we're going to need to standardize how we format things like lists and italics. Something for the style guide.

2022-06-07 16:53 UTC, diana-macrometa commented on docs/streams/quickstart.md
> +# Example
Fix this h1.

2022-06-09 14:06 UTC, diana-macrometa approved these changes
This PR is pretty large. I suggest we merge it and tackle the rest in separate PRs.

2022-06-09 16:18 UTC, dustinlarimer commented on docs/collections/graphs/quickstart.md
> +### Driver download
Should this be title case, match other H2s?

2022-06-09 16:23 UTC, dustinlarimer commented on docs/essentials/introduction.md
> +### Replication Within Datacenter
We should shore up "data center" vs. "datacenter". It appears we use "data center" somewhat consistently on product/landing pages of the website, and "datacenter" here and in the blog.

2022-06-09 16:23 UTC, dustinlarimer commented on docs/essentials/introduction.md
> +### Replication Across Datacenters
Another "datacenter" vs. "data center"

2022-06-09 16:23 UTC, dustinlarimer commented on docs/streams/quickstart.md
> +### Pub-Sub with streams in browser
Sentence-case - switch to title case?

2022-06-09 17:19 UTC, jamesm-macrometa commented on docs/essentials/introduction.md
> +### Replication Within Datacenter
@diana-macrometa We should add a note about this in the style guide if we don't already have one.  Do you prefer "datacenter" or "data center"?

2022-06-09 17:29 UTC, merged