Update spec.json
Macrometacorp/docs pull request #75
Opened 2022-06-08 11:40 UTC by Luba89

PR regarding https://macrometa.atlassian.net/browse/DOC-289

2022-06-08 22:33 UTC, jamesm-macrometa commented on static/swagger/spec.json
> +        "description": "Create collection.\nRequires a JSON object with these properties:\n- **name**: The name of the collection.\n - **keyOptions**:\n    - **allowUserKeys**: If set to *true*, you
```suggestion
        "description": "Create collection.\nRequires a JSON object with these properties:\n- **name**: The name of the collection.\n - **keyOptions**:\n    - **allowUserKeys**: If set to *true*, you can supply a key value in the *_key* attribute of a document. If set to *false*, the key generator creates keys, and an error occurs if you add a *_key* value.\n    - **type**: Choose the type of key generator:\n      - **traditional**: Generates numerical keys in ascending order.\n      - **autoincrement:** Generates numerical keys in ascending order with configurable initial offset and spacing.\n      - **padded:** Generates keys of a fixed length (16 bytes) in ascending lexicographical sort order.\n      - **uuid64**: Generates universally unique keys.\n    - **increment**: Increment value for *autoincrement* key generator. Not used for other key generator types.\n    - **offset**: Initial offset value for *autoincrement* key generator. Not used for other key generator types.\n  - **isSystem**: If *true*, create a system collection. The *collection-name* must start with an underscore. Not Applicable for *end-users*. (The default is *false*)\n  - **isLocal**: If *true*, create a local collection. For a local collection data is not replicated across regions. (The default is *false*)\n - **type**: The type of the collection to be created.\n The following values for *type* are valid (The default is *2*):\n    - *2*: document collection\n    - *3*: edge collection.\n  - **stream**: If *true*, create a local stream for collection. (The default is *false*)\n  - **shardKeys**: The specified shard key determines in which shard a given document is to be stored. Choosing the right shard key can have significant impact on your performance can reduce network traffic and increase performance.",
```

2022-06-08 22:33 UTC, jamesm-macrometa commented on static/swagger/spec.json
> +        "description": "Create collection.\nRequires a JSON object with these properties:\n- **name**: The name of the collection.\n - **keyOptions**:\n    - **allowUserKeys**: If set to *true*, you
Only change here is adding initial capitalization to a few sentences.  Looks good!

2022-06-08 22:33 UTC, jamesm-macrometa requested changes
One minor change, otherwise looks good to me.

2022-06-08 22:34 UTC, jamesm-macrometa commented on static/swagger/spec.json
> +        "description": "Create collection.\nRequires a JSON object with these properties:\n- **name**: The name of the collection.\n - **keyOptions**:\n    - **allowUserKeys**: If set to *true*, you
Oh, just noticed this is the Docs repo and not a Swagger repo!  Incorporating changes and resolving PR.

2022-06-08 22:36 UTC, jamesm-macrometa approved these changes

2022-06-09 16:08 UTC, astrotars approved these changes

2022-06-09 16:11 UTC, merged