DOC-528: Indexes for function folders (Pt. 1)
Macrometacorp/docs pull request #836
Opened 2023-04-07 21:23 UTC by diana-macrometa

This PR improves code block formatting and adds explanation to functions.

It is the first of several PRs that will do this.

2023-04-10 06:35 UTC, StoyanTc requested changes

2023-04-10 06:35 UTC, StoyanTc commented on docs/cep/query-guide/functions/core/log.md
> +from FooStream#log("DEBUG", "Sample Event :", true);
@diana-macrometa - Shall we change the case here for the query?

2023-04-10 06:35 UTC, StoyanTc commented on docs/cep/query-guide/functions/core/log.md
> +```
@diana-macrometa - Shall we change the case here for the query?

2023-04-10 06:35 UTC, StoyanTc commented on docs/cep/query-guide/functions/core/log.md
> +```
@diana-macrometa - Shall we change the case here for the query?

2023-04-10 06:35 UTC, StoyanTc commented on docs/cep/query-guide/functions/core/max.md
>      from fooStream WINDOW TUMBLING_TIME(10 sec);
@diana-macrometa - Shall we change the case here for the query?

2023-04-10 06:35 UTC, StoyanTc commented on docs/cep/query-guide/functions/core/maxForever.md
>      from inputStream;
@diana-macrometa - Shall we change the case here for the query?

2023-04-10 06:35 UTC, StoyanTc commented on docs/cep/query-guide/functions/core/maximum.md
>  select maximum(price1, price2, price3) as max;
@diana-macrometa - Shall we change the case here for the query?

2023-04-10 06:35 UTC, StoyanTc commented on docs/cep/query-guide/functions/core/min.md
>  from inputStream;
@diana-macrometa - Shall we change the case here for the query?

2023-04-10 06:35 UTC, StoyanTc commented on docs/cep/query-guide/functions/core/minForever.md
>  from inputStream;
@diana-macrometa - Shall we change the case here for the query?

2023-04-10 06:35 UTC, StoyanTc commented on docs/cep/query-guide/functions/core/minimum.md
>  select maximum(price1, price2, price3) as max;
@diana-macrometa - Shall we change the case here for the query?

2023-04-10 06:35 UTC, StoyanTc commented on docs/cep/query-guide/functions/core/or.md
>  from cscStream WINDOW TUMBLING_LENGTH(10);
@diana-macrometa - Shall we change the case here for the query?

2023-04-10 06:35 UTC, StoyanTc commented on docs/cep/query-guide/functions/core/unionSet.md
>  from stockStream
@diana-macrometa - Shall we change the case here for the query?

2023-04-10 06:35 UTC, StoyanTc commented on docs/cep/query-guide/functions/core/uuid.md
>  from TempStream;
@diana-macrometa - Shall we change the case here for the query?

2023-04-11 19:46 UTC, jamesm-macrometa commented
Hi @StoyanTc - Diana is off for the week, so I'll be handling this in her stead.  🙂 

Can you please clarify what you mean by "change the case for the query"?  I assume you mean the casing i.e. upper-case or lower-case, but it's not clear to me from looking at the PR what specific change you are requesting.

2023-04-11 20:27 UTC, StoyanTc commented
> Hi @StoyanTc - Diana is off for the week, so I'll be handling this in her stead. 🙂
> 
> Can you please clarify what you mean by "change the case for the query"? I assume you mean the casing i.e. upper-case or lower-case, but it's not clear to me from looking at the PR what specific change you are requesting.

Hi @jamesm-macrometa,

Apologies for my unclear and grammatically not correct comment.
The QL we use into the stream workers is case insensitive. However to make the queries more readable we put all keywords in uppercase. And this is already done everywhere except into the files I have added my comment.

E.g. 
```
insert into RoomTempStream
select convert(roomNo, 'string') as roomNo, temp, UUID() as messageID
from TempStream;
```
should become
```
INSERT INTO RoomTempStream
SELECT convert(roomNo, 'string') AS roomNo, temp, UUID() AS messageID
FROM TempStream;
```

2023-04-11 22:20 UTC, jamesm-macrometa commented
Thanks, @StoyanTc !  I've updated the docs per your suggestion.  Can you please approve the changes so I can merge?

2023-04-12 00:28 UTC, jamesm-macrometa approved these changes

2023-04-12 05:59 UTC, StoyanTc requested changes

2023-04-12 05:59 UTC, StoyanTc commented on docs/cep/query-guide/functions/core/stdDev.md
>  from inputStream;
@jamesm-macrometa - Those lines have left in lower-case.

2023-04-12 05:59 UTC, StoyanTc commented on docs/cep/query-guide/functions/core/sum.md
>  from inputStream;
@jamesm-macrometa - Those lines have left in lower-case.

2023-04-12 19:51 UTC, jamesm-macrometa commented
Thanks again for the catches @StoyanTc !  Just updated per your last comments.  Please approve when ready 🙂

2023-04-12 20:54 UTC, StoyanTc approved these changes

2023-04-12 21:21 UTC, merged