17.17 - Search Views Index
Macrometacorp/docs pull request #938
Opened 2023-07-24 21:27 UTC by diana-macrometa

This PR rewrites the Search Views index so that it covers both Fulltext Search and Semantic Search.

2023-07-25 00:25 UTC, elof reviewed
![Screenshot by Dropbox Capture](https://github.com/Macrometacorp/docs/assets/1088136/cea191db-0a3a-4874-9c6b-2d1314b260b5)

I got some errors for broken markdown links

2023-07-25 09:05 UTC, amolth-macrometa requested changes

2023-07-25 09:05 UTC, amolth-macrometa commented on docs/search-views/index.md
> +Semantic search is a different approach that understands the intent behind a search query and the meanings of words. It uses natural language processing and machine learning techniques to interpret s
While this is the correct definition and description of semantic search, we are only providing similarity search within this umbrella (no natural language queries or intent based search etc.), so it feels a little too grand. Maybe you can add that in 0.17.17 we are providing similarity search within this umbrella and that the objective is to be able to query for similar items within the items stored in GDN (or something like that).

2023-07-25 09:05 UTC, amolth-macrometa commented on docs/search-views/index.md
> +Choosing between fulltext and semantic search views depends on your specific needs. Fulltext search is efficient for exact keyword searches. Semantic search is useful when understanding context, syno
we are not really doing the content/synonyms/intent in 17.17. (kind of same comment as above)

2023-07-25 09:05 UTC, amolth-macrometa commented on docs/search-views/index.md
> +| Memory usage | Lower, stores keywords | Higher, stores vector representations of words |
similarity search stores not just similarity of words, but can also work with objects, images, videos etc.

2023-07-25 09:05 UTC, amolth-macrometa commented on docs/search-views/index.md
> +| Speed | Fast for exact matches | Can be slower due to complexity, but optimized with HNSW, IVF, and FLAT |
I think we don't yet have enough data for this. This anyway depends on the kind of parameters that we use. Not sure this line really provides value to the user.

2023-07-25 13:56 UTC, diana-macrometa commented
> ![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/1088136/255754697-cea191db-0a3a-4874-9c6b-2d1314b260b5.png)
> 
> I got some errors for broken markdown links

Yes, they are fixed in the main release branch. I'm in the middle of rearranging things for the new search.

2023-07-25 15:13 UTC, diana-macrometa commented on docs/search-views/index.md
> +Semantic search is a different approach that understands the intent behind a search query and the meanings of words. It uses natural language processing and machine learning techniques to interpret s
Updated. How's this?

2023-07-25 15:14 UTC, diana-macrometa commented
I removed the comparison table. We can make a new one in future if it seems helpful.

2023-07-25 19:14 UTC, diana-macrometa commented
I added some new content, please re-review.

2023-07-27 05:38 UTC, maheshw2 approved these changes

2023-07-27 14:21 UTC, merged