Add prerender docs index
Macrometacorp/docs pull request #984
Opened 2023-09-25 17:54 UTC by diana-macrometa

This PR adds an index page for Prerendering that explains what the service is, how it works, and lists the features. This content is taken directly from Notion with some minor edits.

2023-09-25 20:00 UTC, diana-macrometa commented on docs/_photoniq/prerendering/index.md
> +Key capabilities include:
```suggestion
Key capabilities of Dynamic Prerendering include:
```

2023-09-26 13:22 UTC, Luba89 commented on docs/_photoniq/prerendering/index.md
> +This process is transparent to the end user. When a user or a search engine crawler makes a request to a website, the server determines whether to serve the dynamic or prerendered version of the site
"When a user or a search engine crawler makes a request to a website, the server determines whether to serve the dynamic or prerendered version of the site. This decision can be based on various factors, such as the type of user agent making the request."
This was something that was planned in the beginning, but now, we are just prerendering. You need to send proper headers, and we will prepare the URL for you. The customer's job is to indefinite the bot and route it on our service.

2023-09-26 13:22 UTC, Luba89 commented on docs/_photoniq/prerendering/index.md
> +- **Authorization**: Access and configuration of the prerender service are safeguarded, requiring user authorization through JWT or API keys.
JWT and API keys are currently not supported. The customer is using a special header to use the service

2023-09-26 16:53 UTC, diana-macrometa commented on docs/_photoniq/prerendering/index.md
> +- **Authorization**: Access and configuration of the prerender service are safeguarded, requiring user authorization through JWT or API keys.
How can I rephrase that? "Access and configuration of the prerender service are safeguarded, requiring special headers for security."?

2023-09-26 16:54 UTC, diana-macrometa commented on docs/_photoniq/prerendering/index.md
> +This process is transparent to the end user. When a user or a search engine crawler makes a request to a website, the server determines whether to serve the dynamic or prerendered version of the site
Should I just remove the whole paragraph, or do we want to reword it?

2023-09-27 16:27 UTC, dlozina-macrometa requested changes
Minor things to change

2023-09-27 16:27 UTC, dlozina-macrometa commented on docs/_photoniq/prerendering/index.md
> +This process is transparent to the end user. When a user or a search engine crawler makes a request to a website, the server determines whether to serve the dynamic or prerendered version of the site
@diana-macrometa could you please reword it according to @Luba89 text? Thanks!

2023-09-27 16:27 UTC, dlozina-macrometa commented on docs/_photoniq/prerendering/index.md
> +- **Authorization**: Access and configuration of the prerender service are safeguarded, requiring user authorization through JWT or API keys.
@diana-macrometa we can just ditch `requiring user authorization through JWT or API keys.`, we will have a login page in the future

2023-09-27 17:08 UTC, diana-macrometa commented on docs/_photoniq/prerendering/index.md
> +This process is transparent to the end user. When a user or a search engine crawler makes a request to a website, the server determines whether to serve the dynamic or prerendered version of the site
How do you "indefinite a bot"?

2023-09-27 17:12 UTC, diana-macrometa commented on docs/_photoniq/prerendering/index.md
> +This process is transparent to the end user. When a user or a search engine crawler makes a request to a website, the server determines whether to serve the dynamic or prerendered version of the site
Guys, I do not know how to translate "You need to send proper headers, and we will prepare the URL for you. The customer's job is to indefinite the bot and route it on our service." into something appropriate for the user.

"When a user or a search engine crawler makes a request to a website,..." what happens? I know that someone has headers somewhere and there are prerendered pages that are getting served somehow.

2023-09-27 17:14 UTC, diana-macrometa commented on docs/_photoniq/prerendering/index.md
> +- **Authorization**: Access and configuration of the prerender service are safeguarded, requiring user authorization through JWT or API keys.
Updated. WDYT?

2023-09-28 08:11 UTC, Luba89 commented on docs/_photoniq/prerendering/index.md
> +This process is transparent to the end user. When a user or a search engine crawler makes a request to a website, the server determines whether to serve the dynamic or prerendered version of the site
@diana-macrometa @dlozina-macrometa, Sorry for the confusion,  I think we can remove it, as we are not using that approach anymore. Currently, we are just receiving requests, and we are then prerendering; we are not checking if someone is a bot or not; that logic now is on the client side.

2023-09-28 14:28 UTC, diana-macrometa commented on docs/_photoniq/prerendering/index.md
> +This process is transparent to the end user. When a user or a search engine crawler makes a request to a website, the server determines whether to serve the dynamic or prerendered version of the site
Done. Btw, I took that text straight out of Notion, so you guys might want to update that.

2023-09-28 14:29 UTC, diana-macrometa commented
Reviewers - Are we ready for approval?

2023-09-28 15:16 UTC, Luba89 approved these changes

2023-09-28 15:19 UTC, diana-macrometa commented
@dlozina-macrometa, I need your approval to unblock this PR and merge.

2023-09-29 13:57 UTC, dlozina-macrometa approved these changes
👍

2023-09-29 14:03 UTC, merged