Prerender API Endpoints
Macrometacorp/docs pull request #987
Opened 2023-09-25 19:27 UTC by diana-macrometa

This PR adds content about API endpoints for Dynamic Prerendering. It will probably be unnecessary once the API References are public.

Reviewers - Please ignore the content in index.md, it is covered in another PR.

2023-09-27 15:21 UTC, dlozina-macrometa requested changes
let's change the `origin` object and that is it

2023-09-27 15:21 UTC, dlozina-macrometa commented on docs/_photoniq/prerendering/prerendering-tasks-api.md
> +    {
{
      "_key": "string",
      "origin": "string",
      "siteMaps": ["string"],
      "ttl": "string",
      "caching": boolean,
      "allowOriginHeaderValue": "string",
      "identifyNotFound":"string",
      "passThroughHeaders":Array,
      "addResponseHeaders":Object,
      "created": Date,
      "lastUpdate": Object
    }
    ```
    
    We have updated origin object @diana-macrometa

2023-09-27 15:21 UTC, dlozina-macrometa commented on docs/_photoniq/prerendering/prerendering-tasks-api.md
> +    jsonCopy code
⬆️ same as the above

2023-09-27 15:40 UTC, diana-macrometa commented on docs/_photoniq/prerendering/prerendering-tasks-api.md
> +    {
Updated

2023-09-27 15:40 UTC, diana-macrometa commented on docs/_photoniq/prerendering/prerendering-tasks-api.md
> +    jsonCopy code
Updated

2023-09-28 14:27 UTC, diana-macrometa commented
@tushar-macrometa, which endpoint did you want me to remove?

2023-09-29 13:58 UTC, dlozina-macrometa approved these changes
👍

2023-10-02 14:50 UTC, diana-macrometa commented
@dlozina-macrometa and @tushar-macrometa - Which endpoint needed to be removed from the docs?

2023-10-02 17:14 UTC, dlozina-macrometa requested changes, later dismissed
small change

2023-10-02 17:14 UTC, ghost commented on docs/_photoniq/prerendering/prerendering-tasks-api.md
> +**Endpoint:** `/api/prerender/v1/purge/cdn`
@diana-macrometa, we need to remove this endpoint `/api/prerender/v1/purge/cdn`

2023-10-02 17:17 UTC, diana-macrometa commented on docs/_photoniq/prerendering/prerendering-tasks-api.md
> +**Endpoint:** `/api/prerender/v1/purge/cdn`
Updated.

Until we get the API Reference into the documentation and public, we will need to update this topic with each new user-facing change.

2023-10-03 00:43 UTC, elof approved these changes
:shipit:

2023-10-03 03:10 UTC, tushar-macrometa commented
> @tushar-macrometa, which endpoint did you want me to remove?

@diana-macrometa  - I wanted to remove Purge CDN cache endpoint but I can see that you already removed it.

2023-10-03 13:16 UTC, tushar-macrometa approved these changes

2023-10-03 18:28 UTC, merged